name: Daily Automation Python Email Scheduler Every 6 Hours

on:
  schedule:
    - cron: "0 */6 * * *" # Every 6 hours
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest
    timeout-minutes: 30 # Prevent jobs from running too long

    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Updated to v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }} # Use token instead of persist-credentials
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11" # Use specific version for consistency

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Run daily job search script
      - name: Run daily job search script
        id: job-search
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
          RAPIDAPI_HOST: ${{ secrets.RAPIDAPI_HOST }}
          RAPIDAPI_URL: ${{ secrets.RAPIDAPI_URL }}
        run: |
          echo "Running job search script..."
          python daily_job_search.py
          echo "Job search script completed"
        continue-on-error: true # Allow workflow to continue if this fails

      # Run daily interview questions script
      - name: Run daily interview questions script
        id: interview-questions
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          echo "Running interview questions script..."
          python daily_interview_questions.py
          echo "Interview questions script completed"
        continue-on-error: true # Allow workflow to continue if this fails

      # Check if history file exists and has changes
      - name: Check for changes
        id: check-changes
        run: |
          if [[ -f "last_questions.json" ]]; then
            if git diff --quiet last_questions.json; then
              echo "No changes to commit"
              echo "changes=false" >> $GITHUB_OUTPUT
            else
              echo "Changes detected"
              echo "changes=true" >> $GITHUB_OUTPUT
            fi
          else
            echo "History file not found, will create it"
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      # Commit and push updated history file only if there are changes
      - name: Commit updated history file
        if: steps.check-changes.outputs.changes == 'true'
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add last_questions.json
          git commit -m "Update interview question history [skip ci]"
          git push

      # Summary step to report results
      - name: Workflow Summary
        if: always()
        run: |
          echo "## Workflow Results" >> $GITHUB_STEP_SUMMARY
          echo "| Script | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|--------|--------|" >> $GITHUB_STEP_SUMMARY

          if [[ "${{ steps.job-search.outcome }}" == "success" ]]; then
            echo "| Job Search | ✅ Success |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| Job Search | ❌ Failed |" >> $GITHUB_STEP_SUMMARY
          fi

          if [[ "${{ steps.interview-questions.outcome }}" == "success" ]]; then
            echo "| Interview Questions | ✅ Success |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| Interview Questions | ❌ Failed |" >> $GITHUB_STEP_SUMMARY
          fi

          if [[ "${{ steps.check-changes.outputs.changes }}" == "true" ]]; then
            echo "| History Update | ✅ Updated |" >> $GITHUB_STEP_SUMMARY
          else
            echo "| History Update | ℹ️ No changes |" >> $GITHUB_STEP_SUMMARY
          fi
