name: Job Search Every 8 Hours

on:
  schedule:
    # Runs every 8 hours at 00:00, 08:00, and 16:00 UTC
    # Which is 5:30 AM, 1:30 PM, and 9:30 PM IST
    - cron: "0 */8 * * *"
  workflow_dispatch: # allows manual run

jobs:
  run-job-search:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run script
        env:
          EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
          RAPIDAPI_KEY: ${{ secrets.RAPIDAPI_KEY }}
          RAPIDAPI_HOST: ${{ secrets.RAPIDAPI_HOST }}
          RAPIDAPI_URL: ${{ secrets.RAPIDAPI_URL }}
        run: python daily_job_search.py
